server {
    listen 3000;
    server_name _;

    location = /healthz {
        default_type application/json;
        return 200 '{"status":"ok"}';
    }

    location / {
        default_type application/json;
        return 200 '{"service":"apptrust-hello-service","version":"1.0.0","stage":"DEV","message":"Hello from JFrog AppTrust sample!"}';
    }
}
