#!/usr/bin/env bash
# ------------------------------------------------------------------------------
# Shared configuration for all AppTrust sample scripts.
# Override any value by exporting it in your shell before sourcing.
# ------------------------------------------------------------------------------
set -euo pipefail

SAMPLE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSION_STATE_FILE="${SAMPLE_ROOT}/.apptrust-version"
if [[ "${APPTRUST_IGNORE_VERSION_STATE:-0}" != "1" && -f "${VERSION_STATE_FILE}" ]]; then
  SAVED_APP_VERSION="$(cat "${VERSION_STATE_FILE}")"
  [[ "${SAVED_APP_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] \
    || { echo "Invalid saved version in ${VERSION_STATE_FILE}" >&2; exit 1; }
  APP_VERSION="${SAVED_APP_VERSION}"
fi

# --- JFrog CLI target ---------------------------------------------------------
# Server ID configured via `jf c add`. Must have AppTrust enabled and use an
# access token (AppTrust does not accept basic auth).
export JF_SERVER_ID="${JF_SERVER_ID:-solenglatest}"

# --- Project & repository layout ---------------------------------------------
# JFrog Project the application will live in. Must exist beforehand.
export JF_PROJECT="${JF_PROJECT:-alex}"

# Docker repositories mapped to each lifecycle stage. Promotion copies from
# the DEV repo onwards; adjust names to match your Artifactory layout.
export DOCKER_REPO_DEV="${DOCKER_REPO_DEV:-${JF_PROJECT}-docker-dev-local}"
export DOCKER_REPO_TEST="${DOCKER_REPO_TEST:-${JF_PROJECT}-docker-test-local}"
export DOCKER_REPO_QA="${DOCKER_REPO_QA:-${JF_PROJECT}-docker-qa-local}"
export DOCKER_REPO_PROD="${DOCKER_REPO_PROD:-${JF_PROJECT}-docker-prod-local}"

# --- Application identity -----------------------------------------------------
export APP_KEY="${APP_KEY:-hello-service}"
export APP_NAME="${APP_NAME:-Hello Service}"
export APP_VERSION="${APP_VERSION:-1.0.0}"
export IMAGE_NAME="${IMAGE_NAME:-apptrust-hello-service}"
export IMAGE_TAG="${IMAGE_TAG:-${APP_VERSION}}"

# --- Lifecycle stages ---------------------------------------------------------
# These names must match environments/stages configured on the platform.
export STAGE_DEV="${STAGE_DEV:-DEV}"
export STAGE_TEST="${STAGE_TEST:-TEST}"
export STAGE_QA="${STAGE_QA:-QA}"
export STAGE_PROD="${STAGE_PROD:-PROD}"

# --- Build info --------------------------------------------------------------
export BUILD_NAME="${BUILD_NAME:-${APP_KEY}-build}"
export BUILD_NUMBER="${BUILD_NUMBER:-${APP_VERSION}}"

# --- Evidence signing --------------------------------------------------------
# ECDSA P-256 keys generated by `jf evd generate-key-pair`.
export KEY_DIR="${KEY_DIR:-${SAMPLE_ROOT}/.keys}"
export KEY_ALIAS="${KEY_ALIAS:-hello-service-evidence-key-v2}"
export PRIVATE_KEY="${PRIVATE_KEY:-${KEY_DIR}/evidence.key}"
export PUBLIC_KEY="${PUBLIC_KEY:-${KEY_DIR}/evidence.pub}"

# --- Registry hostname derived from server ID (used for docker tags) ---------
if [[ -z "${REGISTRY_HOST:-}" ]]; then
  REGISTRY_HOST="$(jf c show "${JF_SERVER_ID}" 2>/dev/null \
    | awk -F'https://' '/JFrog Platform URL:/ {print $2}' \
    | sed 's:/$::')"
  export REGISTRY_HOST
fi

# --- Convenience printer ------------------------------------------------------
say() { printf '\033[1;36m▶ %s\033[0m\n' "$*"; }
ok()  { printf '\033[1;32m✓ %s\033[0m\n' "$*"; }
warn(){ printf '\033[1;33m! %s\033[0m\n' "$*"; }
die() { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

require() { command -v "$1" >/dev/null 2>&1 || die "missing dependency: $1"; }
